name: Python Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        pip install pytest==7.4.0 pytest-cov==4.1.0 mock==5.1.0
        # Install BigQuery dependencies with correct versions
        pip install protobuf==3.20.3
        pip install google-api-core==2.11.0 google-auth==2.16.3 google-cloud-core==2.3.2
        pip install google-cloud-bigquery==3.9.0 grpcio==1.51.3 grpcio-status==1.51.3
        # Install OpenAI and Streamlit
        pip install openai==0.28.0 streamlit==1.12.0
        # Install remaining requirements
        pip install -r requirements.txt --no-deps
    
    - name: Run tests
      run: |
        python tests/run_tests.py
        
    - name: Run coverage
      run: |
        pytest --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: false